### PR TITLE
Resolving- [ add trading view chart ] -Add chart for deposit money 

### PR DESCRIPTION
**Pull request by Tsirov**

### CODE REVIEW

**Comment by Tsirov** [comment]
> add background card, a title and a button to apply the time period

I added card and backgraund, but i think that we do not need button because then the user change date it is automatic make call, without needing to click on a button

**Comment by S-Hristov** [comment]
> > add background card, a title and a button to apply the time period
> 
> I added card and backgraund, but i think that we do not need button because then the user change date it is automatic make call, without needing to click on a button

A button click ensures we ment to take the action and it was not a mistake.

**Comment by Tsirov** [comment]
> > > add background card, a title and a button to apply the time period
> > 
> > 
> > I added card and backgraund, but i think that we do not need button because then the user change date it is automatic make call, without needing to click on a button.
> 
> A button click ensures we ment to take the action and it was not a mistake. Also would it be possible to remove the background lines/lower their opacity as they are too white in the dark mode?

I added button but i cannot change lines color or add opacity.

**Comment by S-Hristov** [comment]
> > > > add background card, a title and a button to apply the time period
> > > 
> > > 
> > > I added card and backgraund, but i think that we do not need button because then the user change date it is automatic make call, without needing to click on a button.
> > 
> > 
> > A button click ensures we ment to take the action and it was not a mistake. Also would it be possible to remove the background lines/lower their opacity as they are too white in the dark mode?
> 
> I added button but i cannot change lines color or add opacity.

It is possible to change the styles or completely remove the background lines, please read the types of the createChart() method

**Pull request merged**
